SELECT
    REVIEW.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM
    (SELECT
        *
    FROM
        REST_INFO
    WHERE
        ADDRESS LIKE '서울%') AS REST_IN_SEOUL
JOIN
    REST_REVIEW REVIEW
ON
    REVIEW.REST_ID = REST_IN_SEOUL.REST_ID
GROUP BY
    REST_IN_SEOUL.REST_ID
ORDER BY
    SCORE DESC,
    FAVORITES DESC
    
# SELECT
#     *   
# FROM
#     REST_INFO I
# JOIN
#     REST_REVIEW RE
# ON
#     I.REST_ID = RE.REST_ID
# WHERE
#     ADDRESS LIKE '서울%'