SELECT
    A.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM
    (SELECT
        M.MEMBER_ID,
        M.MEMBER_NAME,
        RANK() OVER (ORDER BY COUNT(*) DESC) AS RAN
    FROM
        MEMBER_PROFILE M
    JOIN
        REST_REVIEW R
    ON
        M.MEMBER_ID = R.MEMBER_ID
    GROUP BY
        M.MEMBER_ID
    ORDER BY
        RAN) AS A
JOIN
    REST_REVIEW R
ON
    R.MEMBER_ID = A.MEMBER_ID
WHERE
    A.RAN = 1
ORDER BY
    REVIEW_DATE,
    REVIEW_TEXT