SELECT
    MONTH(C.START_DATE) AS MONTH,
    C.CAR_ID,
    COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY C
WHERE
    C.CAR_ID IN (SELECT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN DATE('2022-08-01') AND DATE('2022-10-31')
    GROUP BY
        CAR_ID
    HAVING
        COUNT(*) >= 5)
    AND 
        C.START_DATE BETWEEN DATE('2022-08-01') AND DATE('2022-10-31')
GROUP BY
    MONTH,
    CAR_ID
HAVING
    RECORDS > 0
ORDER BY
    MONTH,
    C.CAR_ID DESC
    