WITH MAX_SIZE_OF_THE_YEAR AS (
    SELECT
        MAX(SIZE_OF_COLONY) AS MAX_SIZE,
        YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR
),
ECOLI_YEAR_DATA AS (
    SELECT
        YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
        MAX_SIZE - ED.SIZE_OF_COLONY AS YEAR_DEV,
        ED.ID
    FROM
        ECOLI_DATA ED
    JOIN
        MAX_SIZE_OF_THE_YEAR MSOTY
    ON
        YEAR(ED.DIFFERENTIATION_DATE) = MSOTY.YEAR
)

SELECT
    YEAR,
    YEAR_DEV,
    ID
FROM
    ECOLI_YEAR_DATA
ORDER BY
    YEAR,
    YEAR_DEV
