SELECT
    I.ID,
    N.FISH_NAME,
    FISH_MAX.MAX_LENGTH AS LENGTH
FROM
    FISH_INFO I JOIN (SELECT
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM
        FISH_INFO
    GROUP BY
        FISH_TYPE) AS FISH_MAX ON I.FISH_TYPE = FISH_MAX.FISH_TYPE
    JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE
    I.LENGTH = FISH_MAX.MAX_LENGTH AND I.FISH_TYPE = FISH_MAX.FISH_TYPE
ORDER BY
    I.ID
