SELECT
    CONDITION_FISH.FISH_COUNT,
    CONDITION_FISH.MAX_LENGTH,
    CONDITION_FISH.FISH_TYPE
FROM
    (SELECT
        COUNT(*) AS FISH_COUNT,
        SUM(IF(LENGTH IS NULL, 10, LENGTH)) / COUNT(*) AS AVG_LENGTH,
        MAX(LENGTH) AS MAX_LENGTH,
        FISH_TYPE
    FROM
        FISH_INFO
    GROUP BY 
        FISH_TYPE
    HAVING
        AVG_LENGTH >= 33) AS CONDITION_FISH
ORDER BY
    CONDITION_FISH.FISH_TYPE